source :gemcutter
gem "ruby_parser"
gem "ruby2ruby"
gem "ParseTree"
gem "diff"
gem "diff-lcs"
gem "minitest"
gem "nokogiri"
gem "arel", "~>0.4"
gem "sqlite3-ruby"
gem "activerecord", "~>3.0.0.beta"
gem "i18n"
gem "json", "1.1.9"
gem "treetop", "~>1.4.8"

