source :rubygems

here = File.expand_path(File.dirname(__FILE__))

gem "rspec", "~> 1.3", :require => "spec"
gem "rvm"
gem "bundler"
gem "rake"

gemspec :path => "#{here}/../../..", :name => "wrong"

