source :rubygems

here = File.expand_path(File.dirname(__FILE__))

gem "rspec", "~> 2.0"
gem "rspec-core", "~> 2.0"
gem "rspec-expectations", "~> 2.0"

gem "rvm"
gem "bundler"
gem "rake"

gemspec :path => "#{here}/../../..", :name => "wrong"
